### ISSUE TITLE
Sustainable Question

### ISSUE THREAD

**Issue by instantkaffee** [jimhester/types#1]
I think the approach of types is really good.
Before I opt in, few questions:
Are you serious about types in R and will you maintain the package longterm?
Will you file in CRAN?

Thx

**Comment by jimhester** [comment]
This package likely won't need much maintenance, it is designed to be very small (and do very little). The seriousness of types in the future is largely dependant on if people use them in their packages, and what other packages take advantage of them.

I will put this on CRAN once we have a few more concrete examples of using types.

**Comment by instantkaffee** [comment]
Thx
